// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: wfjhljukzhjrmsianibw

class SupabaseConfig {
  static const String supabaseUrl = 'https://wfjhljukzhjrmsianibw.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmamhsanVremhqcm1zaWFuaWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwOTA4NTgsImV4cCI6MjA3NDY2Njg1OH0.iF0wo3CG513_CKOGUKMNCj_Fe4dwPALG65Tzd1eioJY';
}
